[[bin]]
name = "nixfmt"
path = "src/main.rs"

[dependencies]
nixfmt = { path = "../nixfmt" }
clap = { version = "*", default-features = false, features = [
  "color",
  "derive",
  "env",
  "std",
  "strsim",
] }
futures = { version = "*", default-features = false, features = [
  "executor",
  "thread-pool",
] }
num_cpus = { version = "*", default-features = false, features = [] }
toml = { version = "*", default-features = false, features = ["parse", "serde"] }
walkdir = { version = "*", default-features = false, features = [] }

[package]
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
description = "The Uncompromising Nix Code Formatter"
edition = "2021"
license = "MIT"
name = "nixfmt_cli"
repository = "https://github.com/kamadorueda/nixfmt"
version = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
