# Configuration options for nixfmt

indentation = "TwoSpaces" # Or: FourSpaces, Tabs
# max_width = 100 # Optional positive integer; omitted disables width wrapping
# align_trailing_comments = true # Optional; defaults to false
