[workspace]

[dependencies]
nixfmt = { "path" = "../nixfmt" }
console_error_panic_hook = "*"
serde_json = "*"
wasm-bindgen = "*"

[lib]
crate-type = ["cdylib"]

[package]
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
description = "The Uncompromising Nix Code Formatter"
edition = "2021"
license = "MIT"
name = "nixfmt_wasm"
repository = "https://github.com/kamadorueda/nixfmt"
version = "0.1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
